# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [14]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [15]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.8742592  0.05270455 0.40905098 ... 0.74311288 0.65110761 0.70330597]
 [0.14766004 0.64828009 0.42619984 ... 0.21449743 0.56214309 0.02577619]
 [0.99632223 0.17496656 0.08158436 ... 0.23762313 0.39579792 0.33113189]
 ...
 [0.62878424 0.12240248 0.83604276 ... 0.11946588 0.67589735 0.11675729]
 [0.35837478 0.20948065 0.29549644 ... 0.36366465 0.53117056 0.57764498]
 [0.30744374 0.51993064 0.24093847 ... 0.84066236 0.40238415 0.12513491]]
[[0.75227809 0.7653606  0.84865064 ... 0.36627698 0.10677172 0.85647301]
 [0.13549577 0.7292739  0.54127861 ... 0.35900134 0.62128362 0.22764631]
 [0.08388799 0.28440387 0.62884327 ... 0.28710601 0.4886983  0.60108943]
 ...
 [0.78996387 0.22783649 0.83802615 ... 0.17464725 0.77605586 0.24598171]
 [0.25191001 0.05330083 0.48894606 ... 0.98177913 0.68710653 0.79708512]
 [0.23988839 0.2303723  0.62405435 ... 0.99667948 0.40369049 0.54007059]]


Без использования numpy

In [16]:
def mult(a, b):
    if len(a[0]) != len(b):
        raise ValueError("Количество столбцов матрицы a должно быть равно количеству строк матрицы b")

    result = []
    for i in range(len(a)):
        row = []
        for j in range(len(b[0])):
            sum = 0
            for k in range(len(b)):
                sum += a[i][k] * b[k][j]
            row.append(sum)
        result.append(row)

    return result

C использованием numpy

In [17]:
import numpy as np

def np_mult(a, b):
    return np.dot(a, b)

In [18]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 652 ms, sys: 0 ns, total: 652 ms
Wall time: 661 ms


In [19]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 1.54 ms, sys: 0 ns, total: 1.54 ms
Wall time: 15 ms


In [20]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.5134560271690134e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [21]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.42118268 0.09505737 0.66698012] [0.94696938 0.710772   0.45827392]


In [22]:
def scalar_product(a, b):
    s = 0
    for i in range(len(a)):
        s += a[i] * b[i]
    return s


In [23]:
def np_scalar_product(a, b):
    return np.dot(a, b)

In [24]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 28 µs, sys: 0 ns, total: 28 µs
Wall time: 31.7 µs
CPU times: user 93 µs, sys: 0 ns, total: 93 µs
Wall time: 97.5 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** numpy написан на более быстром(чем сам python) C и Fortran, так же он использует более оптимизированные и эффективные реализации алгоритмов линейной алгебры, что повышает скорость вычислений.

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [25]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
    diag = np.diag(a)  # Получаем диагональ матрицы
    even_diag = diag[diag % 2 == 0]  # Выбираем четные элементы
    res = np.sum(even_diag) if len(even_diag) > 0 else 0  # Считаем их сумму или возвращаем 0, если таких нет
    return res

In [26]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[5, 7, 1, 5, 6],
       [2, 9, 9, 4, 8],
       [4, 4, 3, 7, 3],
       [2, 2, 2, 3, 7],
       [6, 1, 7, 8, 6]])

In [27]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 336 µs, sys: 0 ns, total: 336 µs
Wall time: 343 µs


6

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [52]:
# функция, решающая задачу с помощью NumPy
import numpy as np
import scipy.stats as sps

def np_sec_av(*args):
    cumsum_args = np.cumsum(np.array(args), axis=1)
    indices = np.arange(1, cumsum_args.shape[1] + 1)
    result = cumsum_args / indices[:, np.newaxis]
    return result

In [53]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[0.43778935 0.46363362 0.18744546 0.79521715 0.33326979 0.88977173
 0.51767851 0.18388245 0.06983668 0.00850824 0.00579557 0.706958
 0.30009716 0.59996772 0.3367331  0.71824519 0.29790662 0.30353772
 0.94662245 0.8548077  0.04557778 0.1900108  0.07087342 0.24067185
 0.41877917 0.77290731 0.62313033 0.00958414 0.70768559 0.12747421
 0.54938808 0.16288197 0.74502948 0.09189935 0.7030822  0.62520925
 0.63561742 0.22280162 0.25606007 0.39770287 0.72761053 0.14414549
 0.62593163 0.52922881 0.99362104 0.31026329 0.72370048 0.5365914
 0.73713093 0.36945749 0.38034356 0.5544814  0.70063489 0.59636968
 0.88778518 0.77078475 0.18256251 0.99171703 0.8412066  0.6123834
 0.42351952 0.6507882  0.98321172 0.71017023 0.11262439 0.58305452
 0.93642298 0.15505634 0.48463326 0.02046301 0.86545525 0.71865961
 0.45160299 0.22600151 0.48224552 0.72815242 0.38333512 0.23565338
 0.46010991 0.38888834 0.99737732 0.33768199 0.77697114 0.12079364
 0.26689758 0.97072234 0.26224679 0.63726062 0.18024153 0.46931407

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [41]:
# функция, решающая задачу с помощью NumPy
import numpy as np

def np_encode(a):
    # Используем функцию np.diff для нахождения изменений в массиве
    changes = np.where(np.diff(a) != 0)[0]

    # Если массив пустой, то каждый элемент повторяется один раз
    if len(changes) == 0:
        return a, np.array([len(a)])

    # Создаем новый массив для элементов и их количества повторений
    elements = np.append(a[changes], a[-1])  # Элементы
    counts = np.diff(np.append(-1, changes))  # Количество повторений

    return elements, counts

In [42]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 301 µs, sys: 26 µs, total: 327 µs
Wall time: 312 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [43]:
# функция, решающая задачу с помощью NumPy
import numpy as np

def np_transformation(X, a=1):
    modified = np.copy(X)
    modified[::2] = modified[::2] ** 3
    modified[1::2] = a

    reversed_modified = np.flip(modified)

    result = np.concatenate((X, reversed_modified))
    return result

In [44]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 1.22 ms, sys: 13 µs, total: 1.23 ms
Wall time: 3.71 ms
